### ISSUE TITLE
[Feature Possibility] 3D Box Arts?

### ISSUE THREAD

**Issue by HarryTheTurtle** [libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System#21]
Would 3D Box Arts be something that would interest the developers and users? Would it go with the aesthetic of RetroArch?

Here is a 3D image I quickly put together for reference.
![Donkey Kong Country 3 - Dixie Kong's Double Trouble! (USA) (En,Fr)](https://user-images.githubusercontent.com/47069190/54484208-74b20f80-482f-11e9-8bad-5ca840c8ff46.png)

I didn't do any measurements. I just eyeballed the skews and scale but I can get it exact if I made a template.
Obviously this would be a massive undertaking for me and I may not have the patience or time but if I found time is this something anyone would want with RetroArch?

**Comment by anewuser** [comment]
Please close this issue and use the main tracker instead: https://github.com/libretro-thumbnails/libretro-thumbnails/issues
