### ISSUE TITLE
[Request Feature] for case "Super Metroid (Japan, USA) (En,Ja)" - Multi Art_box, snaps, titles

### ISSUE THREAD

**Issue by wwark** [libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System#28]
Hi,
Maybe you already think about this case.
The main point is to have the possibility to choose the art box if the rom is distibuted to different country like "Super Metroid (Japan, USA) (En,Ja)" (Japanese BoxArt or USA BoxArt)
(also for the roms with "World" or European have different artbox).

Maybe it will be difficult to implement.
Thanks for your return.

**Comment by RobLoach** [comment]
This may be too much work to both implement and maintain. When there is a dual release, we usually focus on the USA release. If you'd prefer the Japan box, feel free to fork and make the changes there. I'm sure there would be others who may have interest.

**Comment by wwark** [comment]
I will close this ticket.
Thank you for your answer.
