### ISSUE TITLE
Super Ghouls'n Ghosts (Europe) renamed to Super Ghouls 'N Ghosts (Europe) ?

### ISSUE THREAD

**Issue by tatapoum** [libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System#34]
Hi
According to nointro database, it seems that `Super Ghouls'n Ghosts (Europe)` should be renamed to `Super Ghouls 'N Ghosts (Europe)`.

**Comment by RobLoach** [comment]
Feel free to submit a Pull Request and we can get that fix in. Thanks!

**Comment by ner00** [comment]
Wasn't aware of this existing issue, but it seems my last pull request fixed this so this can be closed.

**Comment by RobLoach** [comment]
Wooo!
